spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/rabbitmq_demo
    username: postgres
    password: postgres
